# Generated by Django 4.2.3 on 2024-06-26 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articles',
            options={'verbose_name_plural': 'Article'},
        ),
        migrations.AlterField(
            model_name='articles',
            name='abstract',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Introduction'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='author',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='category',
            field=models.IntegerField(blank=True, choices=[(0, 'Recipes'), (1, 'Nutrition'), (2, 'Culinary Travel'), (3, 'Food Reviews'), (4, 'Other')], null=True, verbose_name='Classification'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='change_date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Revise Date'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='collects_count',
            field=models.IntegerField(default=0, verbose_name='Collections'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='comment_count',
            field=models.IntegerField(default=0, verbose_name='Comments'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='cover',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app01.cover', verbose_name='Article Cover'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Post Date'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='digg_count',
            field=models.IntegerField(default=0, verbose_name='Like'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='Article Link'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='look_count',
            field=models.IntegerField(default=0, verbose_name='Views'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='pwd',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Article Password'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='recommend',
            field=models.BooleanField(default=True, verbose_name='Whether to recommend'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='source',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Source'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='status',
            field=models.IntegerField(choices=[(0, 'unpublished'), (1, 'published')], verbose_name='Save Status'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='tag',
            field=models.ManyToManyField(blank=True, to='app01.tags', verbose_name='Tag'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='word',
            field=models.IntegerField(default=0, verbose_name='Article Word Count'),
        ),
    ]
