# Generated by Django 4.2.3 on 2024-07-11 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_alter_articles_options_alter_articles_abstract_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='category',
            field=models.IntegerField(blank=True, choices=[(1, 'Recipes'), (2, 'Nutrition'), (3, 'Culinary Travel'), (4, 'Food Reviews'), (5, 'Other')], null=True, verbose_name='Classification'),
        ),
    ]
