# Generated by Django 4.2.3 on 2024-08-07 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_alter_articles_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='category',
            field=models.IntegerField(blank=True, choices=[(1, 'Recipes'), (2, 'Restaurant Recommendations'), (3, 'Quick & Easy'), (4, 'Food Reviews'), (5, 'Healthy Eating')], null=True, verbose_name='Classification'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='account_status',
            field=models.IntegerField(choices=[(0, 'Normal'), (1, 'Exception'), (2, 'Be banned')], default=0, verbose_name='账号状态'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='sign_status',
            field=models.IntegerField(choices=[(0, 'Username register'), (1, 'QQ注册'), (2, 'gitee注册'), (3, '手机号注册'), (4, '邮箱注册')], default=0, verbose_name='注册方式'),
        ),
    ]
