# Generated by Django 4.2.3 on 2024-08-08 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_alter_articles_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='login_date',
            field=models.DateTimeField(auto_now=True, verbose_name='登录时间'),
        ),
    ]
