# Generated by Django 4.2.3 on 2024-08-08 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_userinfo_login_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='login_date',
        ),
    ]
