# Generated by Django 4.2.3 on 2024-08-07 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, verbose_name='Emails from sender')),
                ('content', models.TextField(verbose_name='Send context')),
            ],
            options={
                'verbose_name_plural': 'Email Sent',
            },
        ),
    ]
