# Generated by Django 4.2.3 on 2024-08-07 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='create_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Send time'),
        ),
    ]
